import type { ToolConfig, ToolId } from "./types";

export const DEFAULT_API_BASE_URL = "http://localhost:8000";

export const BACKEND_LIMITS = {
  maxFileBytes: 50 * 1024 * 1024,
  maxCombinedUploadBytes: 200 * 1024 * 1024,
  maxFilesPerRequest: 20,
  maxPdfPages: 2_000,
} as const;

export const TOOL_ORDER = [
  "word",
  "powerpoint",
  "excel",
  "merge",
  "split",
  "images",
] as const satisfies readonly ToolId[];

export const TOOL_CONFIGS = {
  word: {
    id: "word",
    slug: "word-to-pdf",
    route: "/word-to-pdf",
    title: "Word to PDF",
    description: "Convert a Word document into a PDF.",
    icon: "word-file",
    endpoint: "/api/convert/docx-to-pdf",
    jobEndpoint: "/api/jobs/docx-to-pdf",
    acceptedExtensions: [".docx"],
    acceptedFormatLabel: ".DOCX",
    acceptAttribute:
      ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    fileFieldName: "file",
    outputKind: "pdf",
    reorderable: false,
    chooseLabel: "Choose a Word file",
    convertLabel: "Convert to PDF",
  },
  powerpoint: {
    id: "powerpoint",
    slug: "ppt-to-pdf",
    route: "/ppt-to-pdf",
    title: "PowerPoint to PDF",
    description: "Convert a PowerPoint presentation into a PDF.",
    icon: "powerpoint-file",
    endpoint: "/api/convert/pptx-to-pdf",
    jobEndpoint: "/api/jobs/pptx-to-pdf",
    acceptedExtensions: [".pptx"],
    acceptedFormatLabel: ".PPTX",
    acceptAttribute:
      ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    fileFieldName: "file",
    outputKind: "pdf",
    reorderable: false,
    chooseLabel: "Choose a PowerPoint file",
    convertLabel: "Convert to PDF",
  },
  excel: {
    id: "excel",
    slug: "excel-to-pdf",
    route: "/excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert an Excel workbook into a PDF.",
    icon: "spreadsheet-file",
    endpoint: "/api/convert/xlsx-to-pdf",
    jobEndpoint: "/api/jobs/xlsx-to-pdf",
    acceptedExtensions: [".xlsx"],
    acceptedFormatLabel: ".XLSX",
    acceptAttribute:
      ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    fileFieldName: "file",
    outputKind: "pdf",
    reorderable: false,
    chooseLabel: "Choose an Excel file",
    convertLabel: "Convert to PDF",
  },
  merge: {
    id: "merge",
    slug: "merge-pdf",
    route: "/merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs in the order you choose.",
    icon: "merge-file",
    endpoint: "/api/pdf/merge",
    jobEndpoint: "/api/jobs/pdf-merge",
    acceptedExtensions: [".pdf"],
    acceptedFormatLabel: ".PDF",
    acceptAttribute: ".pdf,application/pdf",
    multiple: true,
    minFiles: 2,
    maxFiles: BACKEND_LIMITS.maxFilesPerRequest,
    fileFieldName: "files",
    outputKind: "pdf",
    reorderable: true,
    chooseLabel: "Choose PDF files",
    convertLabel: "Merge PDFs",
  },
  split: {
    id: "split",
    slug: "split-pdf",
    route: "/split-pdf",
    title: "Split PDF",
    description: "Separate a PDF into individual pages or page ranges.",
    icon: "split-file",
    endpoint: "/api/pdf/split",
    jobEndpoint: "/api/jobs/pdf-split",
    acceptedExtensions: [".pdf"],
    acceptedFormatLabel: ".PDF",
    acceptAttribute: ".pdf,application/pdf",
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    fileFieldName: "file",
    outputKind: "pdf-or-zip",
    reorderable: false,
    chooseLabel: "Choose a PDF file",
    convertLabel: "Split PDF",
  },
  images: {
    id: "images",
    slug: "images-to-pdf",
    route: "/images-to-pdf",
    title: "Images to PDF",
    description: "Combine images into a PDF in the order you choose.",
    icon: "image-file",
    endpoint: "/api/images/to-pdf",
    jobEndpoint: "/api/jobs/images-to-pdf",
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    acceptedFormatLabel: ".JPG .JPEG .PNG .WEBP",
    acceptAttribute: ".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp",
    multiple: true,
    minFiles: 1,
    maxFiles: BACKEND_LIMITS.maxFilesPerRequest,
    fileFieldName: "files",
    outputKind: "pdf",
    reorderable: true,
    chooseLabel: "Choose image files",
    convertLabel: "Create PDF",
  },
} as const satisfies Readonly<Record<ToolId, ToolConfig>>;

export const TOOLS = TOOL_ORDER.map((toolId) => TOOL_CONFIGS[toolId]);
